### ISSUE TITLE
Interact with nvim-treesitter-textobjects

### ISSUE THREAD

**Issue by Nekketsu** [liangxianzhe/nap.nvim#16]
Is it possible to interact with [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)?

What I mean is the following scenario.
- I have configured the keys `;` and `,` to repeat the move of the last `Text objects: move` action with [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects).
- I'd like to use the same keys `;` and `,` to interact with [nap.nvim](https://github.com/liangxianzhe/nap.nvim).

The issue is that it seems I cannot use the same keymaps in both plugins. If I use the [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) keymaps, then the [nap.nvim](https://github.com/liangxianzhe/nap.nvim) keymaps stop working, and viceversa.

I think that exposing method for going to the next and previous match in [nap.nvim](https://github.com/liangxianzhe/nap.nvim) (`replay(_next)` and `replay(_prev)`) would suffice to configure [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) to use those actions, and both plugins could work together.

I would also be interesting to have methods to repeat the movement in the vim way (; goes to the direction you were moving), or not in the vim way, like [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) does:
- `repeat_last_move_next`: goes forward regardless of the direction you were moving.
- `repeat_last_move_previous`: goes backward regardless of direction you were moving.
- `repeat_last_move`: goes the direction you were moving.
- `repeat_last_move_opposite`: goes the opposite direction you were moving.

**Comment by liangxianzhe** [comment]
Hi @Nekketsu , [added](https://github.com/liangxianzhe/nap.nvim/commit/a82a3a034c8fecdf5b357d1f88f26de6ff5949bb) two APIs for jumping next/prev as you suggested.

However, it is not easy to support `move_opposite` with current implementation. The reason is that the repeat command simply feed the keys (`]x` or `[x`) to trigger the jump. This is to make implementing `expr` (:h :map-expression) easier. One example is that `]c` can use gitsigns in normal buffer and fall back to original `]c` in diff mode.

**Comment by Nekketsu** [comment]
Thank you very much for the update. I really appreciate it. Now I can integrate it with `nvim-treesitter-textobjects`.
